name: "Build fedora-distrobox"

env:
    NAME: fedora-distrobox
    REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Containerfile'
      - '.github/workflows/fedora-distrobox.yml'
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - '.github/workflows/fedora-distrobox.yml'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    container:
      image: quay.io/travier/podman-action@sha256:8d10f0d2bb2df700cf7d87fe932656d1b5289a54f5abdb40ff87429ed78cdec6
      options: "--security-opt=label=disable --privileged --user 0:0 --device=/dev/kvm --device=/dev/fuse --volume /:/run/host:rw"
    steps:
      - name: Fixup GitHub homedir
        run: mkdir -p /github/home/.docker/

      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Build container image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          image: ${{ env.NAME }}
          tags: latest
          containerfiles: ./Containerfile
          layers: false
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          image: ${{ env.NAME }}
          registry: ${{ env.REGISTRY }}
          tags: latest
          extra-args: |
            --compression-format=zstd:chunked
            --compression-level=19

      - name: Login to Container Registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          auth_file_path: /tmp/auth.json